.TH Rscript "1" "April 2007" "R scripting" FSF
.SH NAME
Rscript \- front end for scripting with R
.SH SYNOPSIS
.B Rscript
[\fI--options\fR] [\fI-e expr\fR] \fIfile \fR[\fIargs\fR]
.SH DESCRIPTION
A binary front-end to R, for use in scripting applications.
.TP
\fBexpr\fR
An optional expression to be evaluated, used in place of \fBfile\fR.
.TP
\fBfile\fR
Input file of R expressions
.TP
\fBargs\fR
Optional further arguments to be processed by \fIcommandArgs\fR
in the R interpreter.
.SH OPTIONS
\fB\-\-options\fR accepted are
.TP
\fB\-\-help\fR
Print usage and exit
.TP
\fB\-\-version\fR
Print version and exit
.TP
\fB\-\-verbose\fR
Print information on progress
.TP
\fB\-\-default\-packages\fR=\fIlist\fR
Where 'list' is a comma-separated set
of package names, or 'NULL'
.PP
and also options to R (in addition to \fB\-\-slave\fR \fB\-\-no\-restore\fR),
such as
.TP
\fB\-\-save\fR
Do save workspace at the end of the session
.TP
\fB\-\-no\-environ\fR
Don't read the site and user environment files
.TP
\fB\-\-no\-site\-file\fR
Don't read the site-wide Rprofile
.TP
\fB\-\-no\-init\-file\fR
Don't read the user R profile
.TP
\fB\-\-restore\fR
Do restore previously saved objects at startup
.TP
\fB\-\-vanilla\fR
Combine \fB\-\-no\-save\fR, \fB\-\-no\-restore\fR, \fB\-\-no\-site\-file\fR
\fB\-\-no\-init\-file\fR and \fB\-\-no\-environ\fR
.SH "SEE ALSO"
.BR R(1)
