name: Add to Ecosystem WG Project

on:
  issues:
    types:
      - opened
  pull_request_target:
    types:
      - opened

permissions: {}

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.ECOSYSTEM_ISSUE_TRIAGE_GH_APP_CREDS }}
          org: electron
      - name: Add to Project
        uses: dsanders11/project-actions/add-item@3a81985616963f32fae17d1d1b406c631f3201a1 # v1.1.0
        with:
          field: Opened
          field-value: ${{ github.event.pull_request.created_at || github.event.issue.created_at }}
          project-number: 89
          token: ${{ steps.generate-token.outputs.token }}
